version: "3.8"

services:
  ecommerce_fraud:
    image: postgres:15
    container_name: ecommerce_fraud
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - ecommerce_fraud_data:/var/lib/postgresql/data
      - ./init_scripts/ecommerce_fraud:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - fraud_net

volumes:
  ecommerce_fraud_data:

networks:
  fraud_net:
    driver: bridge